################################################
# title: 2019-2021 EDI Update - SML Transect Data
# author: Lauren Pandori
# started: 7/24/22
# last edited: 7/24/22
###############################################

##### Introduction #####

# This script was written in the summer of 2022 by Lauren Pandori, SML Rocky Intertidal Intern Mentor. This script is based on a script developed by An T Nguyen (EDI Environmental Data Fellow at Shoals Marine Lab in 2018). An's script is available in this repo - 'Cleaning_script.Rmd'. Please email llmpandori@gmail.com with any questions/issues. 

# Shoals Marine Lab Rocky Intertidal Monitoring Data collected between 2019 and 2021 are added to the EDI repository files generated by An T Nguyen in 2018. 

# Some files were not updated since no new information is contributed: 
# transect_info.csv
# 

##### Terms and General Notes ##### 

# Data Structure : The first 5 columns of each sheet are the "core" columns that describe Year, Transect, Level, Replicate and Data_taken (whether or not data were collected). They represent the information that uniquely identifies one row of data, and are kept intact. 


##### packages #####

library(readxl)
library(janitor)
library(tidyverse)

##### presets (file locations, save locations, figure theme) #####

edi_file <- './data/edi_update_data_2021/edi/'
to_add <- './data/edi_update_data_2021/to_add/'

##### category #####

# read in edi file
cat_edi <- read_csv(paste0(edi_file, 'categories_data.csv'),
                         col_types = cols(Replicate = col_character()))

# rgenerate list of dataframes to add to edi data
cat_add <- map(
                # generate list of files to add
                list.files(path = to_add, pattern = 'Transect', 
                           # full file path + all files
                           all.files= T, full.names = T),
                # read 4th sheet of excel file (category data)
                read_xlsx, sheet = 4)

# tidy category data
cat_add2 <- cat_add %>%
  # remove completely empty rows or columns
  map(., remove_empty, which = c('rows', 'cols')) %>%
  map(., mutate_all, as.character)
  # pivot longer so that Organism contains taxonomic info and Category contains the cover estimate

# make list of column names in first 5 columns (ID columns)  
col_list <- unique(unlist(map(map(cat_add2, select, 1:5), colnames)))

spp_cols <- unique(unlist(map(map(cat_add2, select, !1:5), colnames)))

cat3 <- map(cat_add2, pivot_longer, cols %in% spp_cols, 
            names_to = 'Organism', values_to = 'Category')

##### 